# Generated by Django 5.2.4 on 2026-07-12 11:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(max_length=120)),
                ('name_ru', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('season_start_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('season_end_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=80)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30)),
                ('language', models.CharField(choices=[('uz', 'O‘zbek'), ('ru', 'Русский')], default='uz', max_length=2)),
                ('instagram_user_id', models.CharField(max_length=100, unique=True)),
                ('instagram_username', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ai', 'AI javob bermoqda'), ('operator', 'Operatorga o‘tdi'), ('closed', 'Yopildi')], default='ai', max_length=20)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ai_summary', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='core.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.customer')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowerVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(max_length=120)),
                ('name_ru', models.CharField(max_length=120)),
                ('color_uz', models.CharField(max_length=80)),
                ('color_ru', models.CharField(max_length=80)),
                ('default_stems_per_bunch', models.PositiveIntegerField(default=10)),
                ('minimum_sale_stems', models.PositiveIntegerField(default=1)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='core.flower')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(choices=[('customer', 'Mijoz'), ('ai', 'AI'), ('operator', 'Operator'), ('system', 'Tizim')], max_length=20)),
                ('text', models.TextField()),
                ('instagram_message_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('stock_pending', 'Sklad kamaytirilmagan'), ('low_stock', 'Kam qoldiq'), ('lead', 'Yangi lead'), ('handoff', 'Operator kerak')], max_length=30)),
                ('title_uz', models.CharField(max_length=180)),
                ('title_ru', models.CharField(max_length=180)),
                ('body_uz', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packaging_type', models.CharField(choices=[('wrap', 'O‘ram'), ('basket', 'Savat'), ('box', 'Quti'), ('accessory', 'Aksessuar')], max_length=20)),
                ('name_uz', models.CharField(max_length=120)),
                ('name_ru', models.CharField(max_length=120)),
                ('size', models.CharField(blank=True, max_length=40)),
                ('capacity_min_stems', models.PositiveIntegerField(default=1)),
                ('capacity_max_stems', models.PositiveIntegerField(default=999)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging', to='core.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('reel', 'Reel'), ('story', 'Story'), ('ad', 'Target')], max_length=20)),
                ('media_id', models.CharField(max_length=120, unique=True)),
                ('permalink', models.URLField(blank=True)),
                ('title_uz', models.CharField(max_length=180)),
                ('title_ru', models.CharField(max_length=180)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('flower_count', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('is_targeted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_posts', to='core.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('qualified', 'Aniqlangan'), ('contacted', 'Aloqa qilindi'), ('won', 'Sotildi'), ('lost', 'Yo‘qotildi')], default='new', max_length=20)),
                ('request_uz', models.TextField()),
                ('request_ru', models.TextField(blank=True)),
                ('arrangement_type', models.CharField(blank=True, choices=[('bouquet', 'Buket'), ('basket', 'Savat'), ('stems', 'Donalab'), ('catalog', 'Katalog')], max_length=20)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('desired_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(default='instagram', max_length=30)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.branch')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.conversation')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.customer')),
                ('social_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.socialpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='social_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='core.socialpost'),
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(max_length=180)),
                ('name_ru', models.CharField(max_length=180)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('arrangement_type', models.CharField(choices=[('bouquet', 'Buket'), ('basket', 'Savat'), ('box', 'Quti')], max_length=20)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('diameter_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('florist_fee', models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('available', 'Sotuvda'), ('reserved', 'Band'), ('sold', 'Sotildi'), ('archived', 'Arxiv')], default='draft', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('instagram_story_url', models.URLField(blank=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('stock_deducted_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_items', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to=settings.AUTH_USER_MODEL)),
                ('social_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='core.socialpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=40)),
                ('received_at', models.DateField(default=django.utils.timezone.localdate)),
                ('height_cm', models.PositiveIntegerField()),
                ('stems_per_bunch', models.PositiveIntegerField(default=10)),
                ('received_stems', models.PositiveIntegerField()),
                ('remaining_stems', models.PositiveIntegerField()),
                ('cost_per_stem', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_price_per_stem', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_price_per_bunch', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_sale_stems', models.PositiveIntegerField(default=1)),
                ('image_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='core.branch')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.flowervariant')),
            ],
            options={
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_stems', models.PositiveIntegerField()),
                ('quantity_bunches', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='core.catalogitem')),
                ('stock_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_usages', to='core.stockbatch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim'), ('adjustment', 'Tuzatish'), ('waste', 'Hisobdan chiqarish'), ('transfer_out', 'Filialdan chiqim'), ('transfer_in', 'Filialga kirim')], max_length=20)),
                ('quantity_stems', models.IntegerField()),
                ('quantity_bunches', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.stockbatch')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('operator', 'Operator'), ('florist', 'Florist'), ('warehouse', 'Skladchi'), ('content', 'Kontent menejer')], default='operator', max_length=20)),
                ('language', models.CharField(choices=[('uz', 'O‘zbek'), ('ru', 'Русский')], default='uz', max_length=2)),
                ('branches', models.ManyToManyField(blank=True, related_name='staff', to='core.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.UniqueConstraint(fields=('branch', 'batch_number'), name='unique_branch_batch'),
        ),
    ]
