# Generated by Django 5.2.4 on 2026-07-13 15:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_florist_fee', models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=12)),
                ('min_sale_reminder_uz', models.CharField(default='Bu guldan minimal sotilish sonini mijozga ayting.', max_length=255)),
                ('min_sale_reminder_ru', models.CharField(default='Сообщайте клиенту минимальное количество продажи для этого цветка.', max_length=255)),
                ('approximate_price_wording_uz', models.CharField(default='Narx taxminiy, operator aniq tasdiqlab beradi.', max_length=255)),
                ('approximate_price_wording_ru', models.CharField(default='Цена ориентировочная, оператор уточнит итоговую стоимость.', max_length=255)),
                ('handoff_rules_uz', models.TextField(blank=True, default='Telefon raqam olingandan keyin lead yarating va operatorga o‘tkazing.')),
                ('handoff_rules_ru', models.TextField(blank=True, default='После получения телефона создайте лид и передайте оператору.')),
                ('working_hours', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_username', models.CharField(blank=True, max_length=120)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('auto_reply_dm', models.BooleanField(default=True)),
                ('auto_reply_post_reply', models.BooleanField(default=True)),
                ('auto_reply_story_reply', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
