# Generated by Django 5.2.4 on 2026-07-14 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businesssettings_instagramsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Sklad'), ('catalog', 'Katalog'), ('crm', 'CRM'), ('customers', 'Mijozlar'), ('conversations', 'Instagram inbox'), ('social_posts', 'Postlar'), ('notifications', 'Bildirishnomalar'), ('settings', 'Sozlamalar'), ('users', 'Jamoa'), ('audit', 'Audit')], max_length=40)),
                ('can_view', models.BooleanField(default=False)),
                ('can_control', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'page'],
                'constraints': [models.UniqueConstraint(fields=('user', 'page'), name='unique_user_page_permission')],
            },
        ),
    ]
