# Generated by Django 5.2.4 on 2026-07-14 11:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('openai_model', models.CharField(default='gpt-5-mini', max_length=80)),
                ('system_prompt', models.TextField(default='Siz EuroFlowers premium gul do‘konining Instagram sotuvchisiz. Faqat berilgan kontekstdagi qoldiq, katalog va narxlardan foydalaning. Mijoz tilida tabiiy, qisqa va premium ohangda javob bering. O‘zbekcha yoki ruscha yozing. Mavjud bo‘lmagan narx va qoldiqni o‘ylab topmang. Buket hisobida gullar narxiga florist xizmatini qo‘shing. Savatda gul, mos savat va florist xizmatini qo‘shing. Hisoblangan narx taxminiy ekanini ayting. Minimal sotuv soniga rioya qiling. Gul turi noaniq bo‘lsa mavjud variantlarni ko‘rsatib tanlating. Sotuv niyati aniq bo‘lsa ism va telefonni oling. Oldin telefon bo‘lsa maskalangan raqam hali ham ishlashini so‘rang, to‘liq raqamni qayta talab qilmang. Yetkazib berish va to‘lovni va’da qilmang, operator aniqlashtirishini ayting.')),
                ('temperature', models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_access_token', models.TextField(blank=True)),
                ('instagram_account_id', models.CharField(blank=True, max_length=120)),
                ('instagram_business_id', models.CharField(blank=True, max_length=120)),
                ('instagram_verify_token', models.CharField(blank=True, max_length=180)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=180)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='pagepermission',
            name='page',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Sklad'), ('catalog', 'Katalog'), ('crm', 'CRM'), ('customers', 'Mijozlar'), ('conversations', 'Instagram inbox'), ('social_posts', 'Postlar'), ('notifications', 'Bildirishnomalar'), ('settings', 'Sozlamalar'), ('ai_settings', 'AI sozlamalari'), ('integrations', 'Integratsiyalar'), ('users', 'Jamoa'), ('mini_app', 'Mini app'), ('audit', 'Audit')], max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('admin', 'Administrator'), ('operator', 'Operator'), ('florist', 'Florist'), ('warehouse', 'Skladchi'), ('content', 'Kontent menejer')], default='operator', max_length=20),
        ),
    ]
