# Generated by Django 5.2.4 on 2026-07-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aisettings_integrationsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('sender_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('recipient_id', models.CharField(blank=True, max_length=120)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('text', models.TextField(blank=True)),
                ('media_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('story_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('story_url', models.URLField(blank=True)),
                ('postback_referral', models.JSONField(blank=True, default=dict)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
