# Generated by Django 5.2.4 on 2026-07-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_instagramwebhookevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramwebhookevent',
            name='media_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagramwebhookevent',
            name='message_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagramwebhookevent',
            name='recipient_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagramwebhookevent',
            name='sender_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagramwebhookevent',
            name='story_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagramwebhookevent',
            name='story_url',
            field=models.TextField(blank=True),
        ),
    ]
