# Generated by Django 5.2.4 on 2026-07-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_instagramwebhookevent_media_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='instagram_message_id',
            field=models.TextField(blank=True),
        ),
    ]
