# Generated by Django 5.2.4 on 2026-07-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_message_instagram_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='story_share_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='webhook_story_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='webhook_story_url',
            field=models.TextField(blank=True),
        ),
    ]
