# Generated by Django 5.2.4 on 2026-07-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_socialpost_instagram_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='ai_pause_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ai_paused_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
