# Generated by Django 5.2.4 on 2026-07-21 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_catalogitem_quantity_sold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCatalogUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_usages', to='core.catalogitem')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_usage', to='core.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
