# Generated by Django 5.2.4 on 2026-07-21 15:04

from django.db import migrations, models


def seed_lead_statuses(apps, schema_editor):
    LeadStatus = apps.get_model("core", "LeadStatus")
    rows = [
        ("new", "Yangi", "Новый", "#2563eb", 10),
        ("qualified", "Aniqlangan", "Квалифицирован", "#7c3aed", 20),
        ("contacted", "Aloqa qilindi", "Связались", "#f59e0b", 30),
        ("won", "Sotildi", "Продано", "#16a34a", 40),
        ("lost", "Yo‘qotildi", "Потерян", "#dc2626", 50),
    ]
    for key, name_uz, name_ru, color, order in rows:
        LeadStatus.objects.update_or_create(key=key, defaults={"name_uz": name_uz, "name_ru": name_ru, "color": color, "order": order, "is_active": True})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_lead_catalog_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name_uz', models.CharField(max_length=120)),
                ('name_ru', models.CharField(blank=True, max_length=120)),
                ('color', models.CharField(default='#64748b', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='telegram_group_chat_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='recall_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='recall_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='new', max_length=40),
        ),
        migrations.RunPython(seed_lead_statuses, migrations.RunPython.noop),
    ]
