# Generated by Django 5.2.4 on 2026-07-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_aisettings_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowervariant',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flowervariant',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
    ]
