# Generated by Django 5.2.4 on 2026-07-24 12:29

from django.db import migrations, models


def backfill_stock_batch_height_range(apps, schema_editor):
    StockBatch = apps.get_model("core", "StockBatch")
    StockBatch.objects.filter(height_from_cm__isnull=True).update(height_from_cm=models.F("height_cm"))
    StockBatch.objects.filter(height_to_cm__isnull=True).update(height_to_cm=models.F("height_cm"))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_flowervariant_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='height_from_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='height_to_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_stock_batch_height_range, migrations.RunPython.noop),
    ]
