# Generated by Django 5.2.4 on 2026-07-26 11:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_catalogitem_name_ru_remove_flower_name_ru_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='calculated_component_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='calculated_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='catalog_kind',
            field=models.CharField(choices=[('standard', 'Standart'), ('custom', 'Custom')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='volume',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('stock_pending', 'Sklad kamaytirilmagan'), ('low_stock', 'Kam qoldiq'), ('lead', 'Yangi lead'), ('handoff', 'Operator kerak'), ('supplier_stock', 'Postavshik kirimi')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pagepermission',
            name='page',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Sklad'), ('catalog', 'Katalog'), ('crm', 'CRM'), ('customers', 'Mijozlar'), ('conversations', 'Instagram inbox'), ('social_posts', 'Postlar'), ('notifications', 'Bildirishnomalar'), ('suppliers', 'Postavshiklar'), ('florists', 'Floristlar'), ('attendance', 'Ish vaqti'), ('settings', 'Sozlamalar'), ('ai_settings', 'AI sozlamalari'), ('integrations', 'Integratsiyalar'), ('users', 'Jamoa'), ('mini_app', 'Mini app'), ('audit', 'Audit')], max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('admin', 'Administrator'), ('operator', 'Operator'), ('florist', 'Florist'), ('apprentice', 'Shogird'), ('supervisor', 'Nazoratchi'), ('warehouse', 'Skladchi'), ('content', 'Kontent menejer')], default='operator', max_length=20),
        ),
        migrations.CreateModel(
            name='FloristProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_type', models.CharField(choices=[('florist', 'Florist'), ('apprentice', 'Shogird')], default='florist', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('daily_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('work_start_time', models.TimeField(blank=True, null=True)),
                ('work_end_time', models.TimeField(blank=True, null=True)),
                ('shop_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('shop_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('arrival_radius_meters', models.PositiveIntegerField(default=50)),
                ('departure_radius_meters', models.PositiveIntegerField(default=80)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='florists', to='core.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='florist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='FloristAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('source', models.CharField(choices=[('mobile', 'Mobile'), ('manual', 'Qo‘lda')], default='mobile', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('florist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.floristprofile')),
            ],
            options={
                'ordering': ['-work_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='florist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='core.floristprofile'),
        ),
        migrations.CreateModel(
            name='FloristSalaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('catalog', 'Katalog'), ('custom_catalog', 'Custom katalog'), ('daily', 'Kunlik'), ('manual', 'Qo‘lda')], max_length=30)),
                ('work_date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.TextField(blank=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_entries', to='core.floristattendance')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_entries', to='core.catalogitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_entries', to=settings.AUTH_USER_MODEL)),
                ('florist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_entries', to='core.floristprofile')),
            ],
            options={
                'ordering': ['-work_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FloristVolumeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrangement_type', models.CharField(choices=[('bouquet', 'Buket'), ('basket', 'Savat')], max_length=20)),
                ('volume', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
                ('default_stems', models.PositiveIntegerField(default=0)),
                ('florist_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='florist_volume_rates', to='core.branch')),
            ],
            options={
                'ordering': ['arrangement_type', 'volume'],
            },
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='core.supplier'),
        ),
        migrations.AddConstraint(
            model_name='floristattendance',
            constraint=models.UniqueConstraint(fields=('florist', 'work_date'), name='unique_florist_attendance_date'),
        ),
        migrations.AddConstraint(
            model_name='floristsalaryentry',
            constraint=models.UniqueConstraint(fields=('florist', 'source', 'catalog_item'), name='unique_florist_catalog_salary_entry'),
        ),
        migrations.AddConstraint(
            model_name='floristvolumerate',
            constraint=models.UniqueConstraint(fields=('branch', 'arrangement_type', 'volume'), name='unique_branch_arrangement_volume_rate'),
        ),
    ]
