# Generated by Django 5.2.4 on 2026-07-27 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_supplier_catalogitem_calculated_component_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='floristvolumerate',
            name='unique_branch_arrangement_volume_rate',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_method',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='floristvolumerate',
            name='florist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume_rates', to='core.floristprofile'),
        ),
        migrations.AlterField(
            model_name='floristprofile',
            name='shop_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='floristprofile',
            name='shop_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='floristvolumerate',
            constraint=models.UniqueConstraint(fields=('branch', 'florist', 'arrangement_type', 'volume'), name='unique_branch_florist_arrangement_volume_rate'),
        ),
    ]
