# Generated by Django 5.2.4 on 2026-07-27 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_catalogitem_discount_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('stock_pending', 'Sklad kamaytirilmagan'), ('low_stock', 'Kam qoldiq'), ('lead', 'Yangi lead'), ('handoff', 'Operator kerak'), ('supplier_stock', 'Postavshik kirimi'), ('florist_catalog', 'Florist ishi'), ('florist_salary', 'Florist ish haqi'), ('attendance', 'Keldi-ketdi')], max_length=30),
        ),
    ]
