# Generated by Django 5.2.4 on 2026-07-28 08:55

from django.db import migrations, models


def make_branchless_unique_values(apps, schema_editor):
    StockBatch = apps.get_model('core', 'StockBatch')
    seen_batches = {}
    for batch in StockBatch.objects.order_by('batch_number', 'id'):
        key = batch.batch_number
        if key not in seen_batches:
            seen_batches[key] = batch.id
            continue
        batch.batch_number = f"{batch.batch_number}-{batch.id}"
        batch.save(update_fields=['batch_number'])
    FloristVolumeRate = apps.get_model('core', 'FloristVolumeRate')
    seen_rates = {}
    for rate in FloristVolumeRate.objects.order_by('florist_id', 'arrangement_type', 'volume', 'id'):
        key = (rate.florist_id, rate.arrangement_type, rate.volume)
        if key not in seen_rates:
            seen_rates[key] = rate.id
            continue
        rate.volume = f"{rate.volume}-{rate.id}"
        rate.save(update_fields=['volume'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_notification_target_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='floristvolumerate',
            name='unique_branch_florist_arrangement_volume_rate',
        ),
        migrations.RemoveConstraint(
            model_name='stockbatch',
            name='unique_branch_batch',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='floristvolumerate',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='floristprofile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stockbatch',
            name='branch',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(make_branchless_unique_values, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='floristvolumerate',
            constraint=models.UniqueConstraint(fields=('florist', 'arrangement_type', 'volume'), name='unique_florist_arrangement_volume_rate'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.UniqueConstraint(fields=('batch_number',), name='unique_batch_number'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
