# Generated by Django 5.2.4 on 2026-07-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_developer_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floristattendance',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='floristattendance',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='floristattendance',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='floristattendance',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='floristprofile',
            name='shop_latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='floristprofile',
            name='shop_longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
    ]
