# Generated by Django 5.2.4 on 2026-07-29 07:09

from decimal import Decimal
from django.db import migrations, models


def seed_working_hours(apps, schema_editor):
    BusinessSettings = apps.get_model("core", "BusinessSettings")
    for row in BusinessSettings.objects.all():
        hours = row.working_hours or {}
        if not hours.get("uz") or not hours.get("ru"):
            row.working_hours = {
                "uz": hours.get("uz") or "Har kuni 09:00-22:00",
                "ru": hours.get("ru") or "Ежедневно 09:00-22:00",
                "timezone": hours.get("timezone") or "Asia/Tashkent",
            }
            row.save(update_fields=["working_hours"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_ai_prompt_stock_language_pickup_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='delivery_area_ru',
            field=models.CharField(blank=True, default='в пределах города Ташкента', max_length=255),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='delivery_area_uz',
            field=models.CharField(blank=True, default='Toshkent shahri ichida', max_length=255),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='shop_address_ru',
            field=models.CharField(blank=True, default='г. Ташкент, Яккасарайский район, улица Бобур 10', max_length=255),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='shop_address_uz',
            field=models.CharField(blank=True, default='Toshkent shahar, Yakkasaroy tumani, Bobur ko‘chasi 10', max_length=255),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='shop_location_link',
            field=models.CharField(blank=True, default='https://yandex.uz/maps/-/CTfQ6TMD', max_length=255),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='shop_orientir_ru',
            field=models.CharField(blank=True, default='После Next Mall, справа', max_length=255),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='shop_orientir_uz',
            field=models.CharField(blank=True, default='Next Mall dan o‘tgandan keyin o‘ng qo‘lda', max_length=255),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='shop_phone',
            field=models.CharField(blank=True, default='+998 88 009 33 30', max_length=64),
        ),
        migrations.RunPython(seed_working_hours, migrations.RunPython.noop),
    ]
