# Generated by Django 5.2.4 on 2026-07-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_shop_contact_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='desired_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='fulfillment',
            field=models.CharField(blank=True, choices=[('delivery', 'Yetkazib berish'), ('pickup', 'Kelib olish')], max_length=20),
        ),
    ]
