# Generated by Django 5.2.4 on 2026-07-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_ai_prompt_cyrillic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='shop_address_uz_cyril',
            field=models.CharField(blank=True, default='Тошкент шаҳар, Яккасарой тумани, Бобур кўчаси 10', max_length=255),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='shop_orientir_uz_cyril',
            field=models.CharField(blank=True, default='Next Mall дан ўтгандан кейин ўнг қўлда', max_length=255),
        ),
    ]
