# Generated by Django 5.2.4 on 2026-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_ai_prompt_address_and_price_wording'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='reasoning_effort',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('low', 'Past'), ('medium', 'O‘rta'), ('high', 'Yuqori')], default='low', max_length=10),
        ),
    ]
