# Generated by Django 5.2.4 on 2026-07-30 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_ai_prompt_floristika'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='core.customer'),
        ),
    ]
