# Generated by Django 5.2.4 on 2026-07-30 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_catalog_item_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloristFaceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True)),
                ('descriptor', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_face_samples', to=settings.AUTH_USER_MODEL)),
                ('florist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_samples', to='core.floristprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FloristDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('kind', models.CharField(choices=[('weekend', 'Dam kuni'), ('vacation', "Ta'til"), ('sick', 'Kasallik'), ('other', 'Boshqa')], default='weekend', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_days_off', to=settings.AUTH_USER_MODEL)),
                ('florist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='core.floristprofile')),
            ],
            options={
                'ordering': ['-work_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('florist', 'work_date'), name='unique_florist_day_off')],
            },
        ),
        migrations.CreateModel(
            name='FloristStockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remaining_stems', models.PositiveIntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='florist_balances', to='core.stockbatch')),
                ('florist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='core.floristprofile')),
            ],
            options={
                'ordering': ['florist_id', 'batch_id'],
                'constraints': [models.UniqueConstraint(fields=('florist', 'batch'), name='unique_florist_batch_balance')],
            },
        ),
        migrations.CreateModel(
            name='FloristStockIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('issue', 'Chiqarildi'), ('return', 'Qaytarildi'), ('waste', 'Chiqit')], default='issue', max_length=20)),
                ('quantity_stems', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='florist_issues', to='core.stockbatch')),
                ('florist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_issues', to='core.floristprofile')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='florist_stock_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['florist', 'batch'], name='core_floris_florist_502cab_idx')],
            },
        ),
    ]
