# Generated by Django 5.2.4 on 2026-07-31 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_branches(apps, schema_editor):
    Branch = apps.get_model("core", "Branch")
    Branch.objects.get_or_create(name="Asosiy filial", defaults={"is_main": True})
    Branch.objects.get_or_create(name="Parkent filiali", defaults={"is_main": False})


def unseed_branches(apps, schema_editor):
    apps.get_model("core", "Branch").objects.filter(name__in=["Asosiy filial", "Parkent filiali"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_ai_prompt_catalog_from_stock_flower'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['-is_main', 'name'],
            },
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_items', to='core.catalogitem'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='source_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_items', to='core.branch'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.branch'),
        ),
        migrations.CreateModel(
            name='CatalogTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('source_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_transfers', to=settings.AUTH_USER_MODEL)),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='core.catalogitem')),
                ('target_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='core.catalogitem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(seed_branches, unseed_branches),
    ]
