# Generated by Django 5.2.4 on 2026-08-04 11:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_catalog_waste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepermission',
            name='page',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Sklad'), ('catalog', 'Katalog'), ('crm', 'CRM'), ('customers', 'Mijozlar'), ('conversations', 'Instagram inbox'), ('social_posts', 'Postlar'), ('notifications', 'Bildirishnomalar'), ('suppliers', 'Postavshiklar'), ('florists', 'Floristlar'), ('attendance', 'Ish vaqti'), ('settings', 'Sozlamalar'), ('ai_settings', 'AI sozlamalari'), ('integrations', 'Integratsiyalar'), ('users', 'Jamoa'), ('mini_app', 'Mini app'), ('expenses', 'Rasxodlar'), ('audit', 'Audit')], max_length=40),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(choices=[('rent', 'Ijara'), ('utilities', 'Kommunal (svet, suv, gaz)'), ('salary', 'Oylik / avans'), ('transport', 'Transport / dastafka'), ('supplies', 'Xo‘jalik mollari'), ('marketing', 'Reklama'), ('tax', 'Soliq / yig‘im'), ('repair', 'Ta’mirlash'), ('food', 'Oshxona'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('destination', models.CharField(help_text='Qayerga ketdi', max_length=200)),
                ('note', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', 'O‘tkazma')], default='cash', max_length=20)),
                ('spent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-spent_at', '-id'],
                'indexes': [models.Index(fields=['spent_at'], name='core_expens_spent_a_058b49_idx'), models.Index(fields=['category', 'spent_at'], name='core_expens_categor_cb60a7_idx')],
            },
        ),
    ]
