# Generated by Django 5.2.4 on 2026-08-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_expense_page_permission'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='core_expens_categor_cb60a7_idx',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
    ]
