# Generated by Django 5.2.4 on 2026-08-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_remove_expense_core_expens_categor_cb60a7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='sale_bot_token',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='branch',
            name='sale_group_chat_id',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
