# Generated by Django 5.2.4 on 2026-08-05 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_branch_sale_bot_token_branch_sale_group_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='quantity_reworked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cataloghistory',
            name='action',
            field=models.CharField(choices=[('created', 'Qo‘shildi'), ('updated', 'O‘zgartirildi'), ('sold', 'Sotildi'), ('wasted', 'Chiqitga chiqarildi'), ('inventory_deducted', 'Sklad kamaytirildi'), ('inventory_restored', 'Sklad qaytarildi'), ('reworked', 'Restavratsiya qilindi')], max_length=30),
        ),
        migrations.AlterField(
            model_name='floristsalaryentry',
            name='source',
            field=models.CharField(choices=[('catalog', 'Katalog'), ('custom_catalog', 'Custom katalog'), ('decoration', 'Oformleniya'), ('sale_decoration', 'Sotuv oformleniya'), ('daily', 'Kunlik'), ('rework', 'Restavratsiya'), ('manual', 'Qo‘lda')], max_length=30),
        ),
        migrations.CreateModel(
            name='CatalogRework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('florist_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('input_stems', models.PositiveIntegerField(default=0)),
                ('output_stems', models.PositiveIntegerField(default=0)),
                ('waste_stems', models.PositiveIntegerField(default=0)),
                ('input_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('waste_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_reworks', to=settings.AUTH_USER_MODEL)),
                ('florist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reworks', to='core.floristprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='floristsalaryentry',
            name='rework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_entries', to='core.catalogrework'),
        ),
        migrations.CreateModel(
            name='CatalogReworkOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('stems', models.PositiveIntegerField(default=0)),
                ('allocated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allocated_florist_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rework_outputs', to='core.catalogitem')),
                ('rework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='core.catalogrework')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogReworkSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('stems', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rework_sources', to='core.catalogitem')),
                ('rework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.catalogrework')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogReworkStockInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_stems', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_inputs', to='core.catalogrework')),
                ('stock_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rework_inputs', to='core.stockbatch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
