# Generated by Django 5.2.4 on 2026-08-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_ai_prompt_catalog_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='floristsalaryentry',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floristsalaryentry',
            name='unit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='floristsalaryentry',
            name='source',
            field=models.CharField(choices=[('catalog', 'Katalog'), ('custom_catalog', 'Custom katalog'), ('decoration', 'Oformleniya'), ('sale_decoration', 'Sotuv oformleniya'), ('extra_decoration', 'Qo‘shimcha oformleniya'), ('daily', 'Kunlik'), ('rework', 'Restavratsiya'), ('manual', 'Qo‘lda')], max_length=30),
        ),
    ]
