# Generated by Django 5.2.4 on 2026-08-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_move_manual_decoration_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowervariant',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flowervariant',
            name='color_uz',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='flowervariant',
            name='name_uz',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='flowervariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_general', True)), fields=('flower',), name='unique_general_flower_variant'),
        ),
    ]
