# Generated by Django 5.2.4 on 2026-08-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_ai_prompt_media_matching_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicatalogitem',
            name='fingerprint_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aicatalogitem',
            name='fingerprint_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aicatalogitem',
            name='visual_fingerprint',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
